# Generated by Django 3.2.14 on 2022-08-23 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_remove_comment_approved_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment_body',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='commenter_name',
        ),
    ]
