# Generated by Django 3.2.14 on 2022-08-23 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_auto_20220823_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter_name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_body',
            new_name='text',
        ),
    ]
