# Generated by Django 3.2.14 on 2022-08-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0008_comment_approved_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
